### PR TITLE
Idempotency

### PR DESCRIPTION
**Pull request by bukzor**
@chriskuehl @asottile

### CODE REVIEW

**Comment by bukzor** [comment]
yes. derp.

**Comment by asottile** [comment]
weird wonder why travis-ci hasn't run yet

**Comment by bukzor** [comment]
Maybe it was hooked to my account somehow?
It's worked on the same SHA in my fork:
https://travis-ci.org/bukzor/ephemeral-port-reserve-1/jobs/258366491

**Comment by asottile** [comment]
@tomelm can you make sure travis-ci is set up properly for this repository (I also can't merge this branch)

**Comment by bukzor** [comment]
This patch is wrong. It's `s2` that should have a try-bind.

**Comment by tomelm** [comment]
Should be on now

**Pull request merged**
